version: '3.8'

services:

  mongodb:
    image: mongo:6
    container_name: pmbcloud-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - pmbcloud-shared-network
    restart: unless-stopped
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pmbcloud-backend
    ports:
      - "3001:3001"
    volumes:
      - ./src/uploads:/app/src/uploads

    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=http://localhost:5173,http://frontend:5173
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: unless-stopped
    networks:
      - pmbcloud-shared-network
    env_file:
      - .env


networks:
  pmbcloud-shared-network:
    external: true
    name: pmbcloud-shared-network 